# Generated by Django 3.1 on 2020-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('Web', 'Web Develoment'), ('Mobile', 'Mobile Apps')], max_length=200)),
            ],
        ),
    ]
