# Generated by Django 3.0.8 on 2020-08-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200813_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
