# Generated by Django 3.0.8 on 2020-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200817_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_profile.jpg', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
