# Generated by Django 3.0.8 on 2020-08-17 10:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200817_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='processed_image',
            field=imagekit.models.fields.ProcessedImageField(default='post_images/default_post.jpg', null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='processed_profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
