# Generated by Django 3.0.8 on 2020-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200817_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='processed_image',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='processed_profile_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_post.jpg', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
