# Generated by Django 3.0.8 on 2020-08-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200820_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_profile_img',
            new_name='author_profile_pic',
        ),
    ]
