# Generated by Django 3.0.8 on 2020-08-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200825_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
