# Generated by Django 3.0.8 on 2020-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200828_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
