# Generated by Django 3.0.8 on 2020-08-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200828_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.jpg', null=True, upload_to=''),
        ),
    ]
