# Generated by Django 3.0.8 on 2020-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200828_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
